//------------------------------------------------------------------------------
// <auto-generated>
//    Tento kód byl generován ze šablony.
//
//    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
//    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Torchiver.Archiver.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public int FileId { get; set; }
        public string Path { get; set; }
        public string Size { get; set; }
        public string Ed2K { get; set; }
        public string StartBlock { get; set; }
        public string EndBlock { get; set; }
        public string Md5 { get; set; }
        public string Sha { get; set; }
        public int InfoInfoId { get; set; }
    
        public virtual Info Info { get; set; }
    }
}
