//------------------------------------------------------------------------------
// <auto-generated>
//    Tento kód byl generován ze šablony.
//
//    Ruční změny tohoto souboru mohou způsobit neočekávané chování v aplikaci.
//    Ruční změny tohoto souboru budou přepsány, pokud bude kód vygenerován znovu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Torchiver.Archiver.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Info
    {
        public Info()
        {
            this.File = new HashSet<File>();
            this.Tracker = new HashSet<Tracker>();
        }
    
        public int InfoId { get; set; }
        public string Name { get; set; }
        public string FileName { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedDate { get; set; }
        public string BlockSize { get; set; }
        public string BlockCount { get; set; }
        public string FileCount { get; set; }
        public string IsPrivate { get; set; }
        public string Sha { get; set; }
        public string Ed2K { get; set; }
        public string MagnetUrl { get; set; }
        public string Comment { get; set; }
    
        public virtual ICollection<File> File { get; set; }
        public virtual ICollection<Tracker> Tracker { get; set; }
    }
}
