using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using System.IO;
using ArachNGIN.Files;
using ArachNGIN.Files.Streams;
using ArachNGIN.Files.Strings;
using System.Security.Permissions;

namespace PakCreator
{
    public partial class FormMain : Form
    {
        public FormMain()
        {
            InitializeComponent();
        }

        private void btnStart_Click(object sender, EventArgs e)
        {
            DateTime starttime = DateTime.Now;
            if ((txtPak.Text == string.Empty) || (txtDir.Text == string.Empty))
            {
                MessageBox.Show("Musíte zadat adresář pro zabalení i název výstupního souboru!");
                return;
            }
            if (!Directory.Exists(txtDir.Text))
            {
                MessageBox.Show("Zvolený adresář neexistuje!");
                return;
            }
            if (!Directory.Exists(Path.GetDirectoryName(txtPak.Text)))
            {
                MessageBox.Show("Zadaný název PAK souboru není platný!");
                return;
            }
            txtDir.Text=StringUtils.strAddSlash(txtDir.Text);
            string startpath = txtDir.Text;
            string pak_file = txtPak.Text;
            // mru
            if (!txtDir.Items.Contains(startpath)) txtDir.Items.Add(startpath);
            if (!txtPak.Items.Contains(pak_file)) txtPak.Items.Add(pak_file);
            //
            DisableControls(this, false);
            Log("Searching " + txtDir.Text);
            MultimaskFileSearcher srch = new MultimaskFileSearcher();
            srch.Recursive = true;
            srch.SearchExtensions.Add("*.*");
            FileInfo[] path_files = srch.Search(txtDir.Text);
            if (path_files.Length < 1)
            {
                MessageBox.Show("Zadaný adresář je prázdný!");
                return;
            }
            Log("Found " + path_files.Length.ToString() + " files");
            int filecounter = 0;
            StringCollection file_index = new StringCollection();
            //
            file_index.Add("; PakFile Index! Autogenerated on " + DateTime.Now.ToString());
            file_index.Add("; Generator: " + Application.ProductName + " " + Application.ProductVersion);
            file_index.Add("");
            file_index.Add("[Index]");
            file_index.Add("FileCount="+path_files.Length.ToString());
            file_index.Add("");
            //
            QuakePAK.CreateNewPak(pak_file);
            QuakePAK NewPAK = new QuakePAK(pak_file, true);
            Log("Created a new PAK: " + pak_file);
            //
            foreach (FileInfo fi in path_files)
            {
                filecounter++;
                // guidy jsou lepsi nez jen cisla.
                //string tf = StringUtils.PadNumToLength(filecounter, 10);
                Guid g = Guid.NewGuid();
                string tf = g.ToString();
                string fn = fi.FullName;
                //
                fn = fn.Replace(startpath, "");
                fn = fn.Replace("\\", "/"); // prevest normalni lomitka na unixovy
                file_index.Add(fn + "=" + Path.GetFileName(tf));
                Log("Adding to PAK: " + Path.GetFileName(fi.FullName));
                NewPAK.AddFile(fi.FullName, tf, false);
            }
            Log("Writing Index file");
            Stream idx = new MemoryStream();
            StringCollections.SaveToStream(idx, file_index);
            NewPAK.AddStream(idx, "(pak-index)",true);
            idx.Close();
            Log("Closing PAK file");
            NewPAK.Close();
            DateTime endtime = DateTime.Now;
            Log("Start: "+starttime.ToString());
            Log("End: "+endtime.ToString());
            TimeSpan t = endtime - starttime;
            Log("Time: " + t.ToString());
            Log("ALL DONE !!!");
            DisableControls(this, true);
        }

        private void btnOpenDir_Click(object sender, EventArgs e)
        {
            if (browseDir.ShowDialog() == DialogResult.OK)
            {
                txtDir.Text = StringUtils.strAddSlash(browseDir.SelectedPath);
            }
        }

        private void btnSavePak_Click(object sender, EventArgs e)
        {
            if (savePak.ShowDialog() == DialogResult.OK)
            {
                txtPak.Text = savePak.FileName;
            }

        }

        private void Log(string text)
        {
            Application.DoEvents();
            int i = listOutput.Items.Add(text);
            listOutput.SelectedIndex = i;
            Application.DoEvents();
        }

        protected void DisableControls(Control parent, bool enabled)
        {
            foreach (Control c in parent.Controls)
            {
                if (c is ListBox)
                {
                    ((ListBox)(c)).Enabled = true;
                }
                else c.Enabled = enabled;
                DisableControls(c, enabled);
            }
        }

        private void FormMain_FormClosing(object sender, FormClosingEventArgs e)
        {
            Properties.Settings.Default.Save();
        }


        private void button1_Click(object sender, EventArgs e)
        {
            // na otestovani pak filesystemu
            QuakePAKFilesystem QFS = new QuakePAKFilesystem(Program.ATemp.AppDir, Program.ATemp.AppTempDir);
            MessageBox.Show("created");
            MessageBox.Show(QFS.AskFile("Project v1.6/MP4Box/TODO").ToString());
            MessageBox.Show(QFS.AskFile("delphi-webp\\.svn\\entries").ToString());
            MessageBox.Show(QFS.AskFile("0000000083").ToString());
            MessageBox.Show(QFS.AskFile("arachngin.files.dll").ToString());

        }
    }
}
